import { leerAlmacenamiento } from './system-storage';
import { ActividadSistema } from '../system-activity/system-activity.service';
import { inject, Injectable, signal } from '@angular/core';
import { DatosPortfolio } from '../models/portfolio.model';

export type Idioma = 'es' | 'en';

const CLAVE_ALMACENAMIENTO = 'drp-os.language.v1';

const TEXTOS_ESPANOL = {
  'app.loadingLabel': 'Cargando portfolio',
  'app.loadingProfile': 'Cargando perfil profesional...',
  'app.errorTitle': 'No se ha podido cargar el perfil.',
  'app.errorDescription': 'Comprueba que la API está disponible y vuelve a intentarlo.',
  'app.retry': 'Reintentar',
  'shell.portfolioLabel': 'Portfolio interactivo de Daniel Ramón Pérez',
  'shell.desktopLabel': 'Escritorio de Daniel',
  'shell.applicationsLabel': 'Aplicaciones del escritorio',
  'action.open': 'Abrir',
  'action.openNewTab': 'Abrir {{name}} en una pestaña nueva',
  'action.minimize': 'Minimizar {{name}}',
  'action.maximize': 'Maximizar {{name}}',
  'action.restore': 'Restaurar {{name}}',
  'action.close': 'Cerrar {{name}}',
  'taskbar.label': 'Barra de tareas',
  'taskbar.start': 'Inicio',
  'taskbar.openApplications': 'Aplicaciones abiertas',
  'taskbar.localTime': 'Hora local',
  'taskbar.languageSelector': 'Seleccionar idioma',
  'taskbar.spanish': 'Español',
  'taskbar.english': 'Inglés',
  'startMenu.label': 'Menú Inicio',
  'startMenu.reset': 'Restablecer disposición del escritorio',
  'startMenu.restart': 'Reiniciar equipo',
  'restart.status': 'El equipo se está reiniciando',
  'restart.title': 'Reiniciando',
  'restart.shuttingDown': 'Cerrando aplicaciones...',
  'restart.booting': 'Restaurando el escritorio...',
  'restart.systemMessage': 'MEMORIA OK · ARCHIVOS OK · RESTAURANDO SESIÓN',
  'application.about.label': 'Sobre mí',
  'application.about.title': 'Sobre mí',
  'application.work.label': 'Experiencia laboral',
  'application.work.title': 'Experiencia laboral',
  'application.linkedin.label': 'LinkedIn',
  'application.linkedin.title': 'LinkedIn',
  'application.education.label': 'Formación.txt',
  'application.education.title': 'Formación.txt - Bloc de notas',
  'application.source.label': 'Código fuente',
  'application.source.title': 'Código fuente',
  'application.pdf.label': 'Daniel_Ramon_Perez_CV.pdf',
  'application.pdf.title': 'Daniel_Ramon_Perez_CV.pdf - Visor',
  'application.terminal.label': 'Terminal.exe',
  'application.terminal.title': 'Terminal.exe',
  'application.hire.label': 'Contratar',
  'application.hire.title': 'Enviar una oferta',
  'application.paint.label': 'Paint 98',
  'application.paint.title': 'sin título - Paint 98',
  'application.solitaire.label': 'Solitario',
  'application.solitaire.title': 'Solitario',
  'application.minesweeper.label': 'Buscaminas',
  'application.minesweeper.title': 'Buscaminas',
  'application.messageBoard.label': 'Message Board',
  'application.messageBoard.title': 'Message Board',
  'application.taskManager.label': 'Administrador de tareas',
  'application.taskManager.title': 'Administrador de tareas',
  'application.drpExplorer.label': 'DRP Explorer',
  'application.drpExplorer.title': 'DRP Explorer',
  'application.audioPlayer.label': 'Reproductor',
  'application.audioPlayer.title': 'Reproductor',
  'application.music.label': 'Música',
  'application.music.title': 'Música',
  'application.photoAlbum.label': 'Álbum de fotos',
  'application.photoAlbum.title': 'Álbum de fotos',
  'application.recycle.label': 'Papelera de reciclaje',
  'application.recycle.title': 'Papelera de reciclaje',
  'application.welcome.label': 'Bienvenido',
  'application.welcome.title': 'Bienvenido',
  'application.experience.label': 'Experiencia',
  'application.sourceMessage.title': 'Información',
  'window.notepad': 'Bloc de notas',
  'window.imageViewer': 'Visor de imágenes',
  'welcome.eyebrow': 'Bienvenido',
  'welcome.presentationIntro': '¡Hola! Soy Dani Ramón Pérez, desarrollador Full-Stack con más de 3 años de experiencia.',
  'welcome.presentationExplore': 'Este CV está hecho para explorarlo: abre carpetas, mueve cosas y curiosea hasta encontrar lo que buscas sobre mí.',
  'welcome.presentationMess': 'Si dejas el escritorio hecho un desastre, no pasa nada: puedes',
  'welcome.presentationRestart': 'reiniciar el sistema desde Start',
  'welcome.mainTechnologies': 'Tecnologías principales',
  'welcome.quickAccess': 'Accesos rápidos',
  'welcome.work': 'Experiencia laboral',
  'welcome.about': 'Sobre mí',
  'welcome.viewCv': 'Ver CV',
  'welcome.source': 'Código fuente',
  'welcome.hint': 'Consejo: selecciona un icono y pulsa Enter, o haz doble clic para abrirlo.',
  'welcome.restApis': 'APIs REST',
  'about.tabsLabel': 'Propiedades del perfil',
  'about.tab.general': 'General',
  'about.tab.profile': 'Perfil',
  'about.tab.technologies': 'Tecnologías',
  'about.tab.contact': 'Contacto',
  'about.portraitAlt': 'Retrato pixel-art de Daniel Ramón Pérez',
  'about.systemInformation': 'Información del sistema',
  'about.mainFrontend': 'Frontend principal:',
  'about.mainBackend': 'Backend principal:',
  'about.database': 'Base de datos:',
  'about.otherTechnologies': 'Otras tecnologías:',
  'about.language': 'Idioma:',
  'about.specialty': 'Especialidad:',
  'about.specialtyText': 'Aplicaciones web y sistemas de gestión, software hospitalario, ERP, APIs REST y lógica de negocio.',
  'about.professionalProfile': 'Perfil profesional',
  'about.demonstratedCompetencies': 'Competencias demostradas',
  'about.cvTechnologies': 'Tecnologías del CV',
  'about.explicitTechnologies': 'Esta lista contiene únicamente tecnologías mencionadas explícitamente en el currículum.',
  'about.group.frontend': 'Frontend y lenguajes web',
  'about.group.backend': 'Backend y lenguajes',
  'about.group.database': 'Base de datos',
  'about.group.other': 'Otras herramientas',
  'about.contact': 'Contacto',
  'about.location': 'Ubicación',
  'about.email': 'Correo electrónico',
  'about.phone': 'Teléfono',
  'about.openProfile': 'Abrir perfil',
  'about.accept': 'Aceptar',
  'about.apply': 'Aplicar',
  'menu.explorer': 'Menú del Explorador',
  'menu.notepad': 'Menú del Bloc de notas',
  'menu.file': 'Archivo',
  'file.download': 'Descargar...',
  'menu.edit': 'Edición',
  'menu.view': 'Ver',
  'menu.help': 'Ayuda',
  'menu.search': 'Buscar',
  'explorer.back': 'Atrás',
  'explorer.address': 'Dirección',
  'explorer.workPath': 'C:\\Portafolio\\Experiencia laboral',
  'explorer.professionalFiles': 'Archivos de experiencia profesional',
  'explorer.addedItems': 'Elementos añadidos a esta carpeta',
  'explorer.moveToDesktop': 'Mover al escritorio',
  'explorer.objects': '{{count}} objeto(s)',
  'explorer.folderContents': 'Contenido de la carpeta',
  'notepad.persistedStatus': 'Editable · Los cambios se conservan al recargar y se borran al reiniciar el equipo.',
  'context.new': 'Nuevo',
  'context.newFolder': 'Carpeta',
  'context.newText': 'Documento de texto',
  'context.sort': 'Ordenar iconos',
  'context.sortName': 'Por nombre',
  'context.sortType': 'Por tipo',
  'context.sortCreated': 'Por fecha de creación',
  'context.sortOriginal': 'Orden original',
  'context.align': 'Alinear iconos',
  'context.refresh': 'Actualizar',
  'context.open': 'Abrir',
  'context.edit': 'Editar',
  'context.cut': 'Cortar',
  'context.copy': 'Copiar',
  'context.paste': 'Pegar',
  'context.rename': 'Cambiar nombre',
  'context.sendTo': 'Enviar a',
  'context.sendDesktop': 'Escritorio',
  'context.sendWork': 'Experiencia laboral',
  'context.sendMusic': 'Música',
  'context.sendRecycle': 'Papelera de reciclaje',
  'context.delete': 'Eliminar',
  'context.restore': 'Restaurar',
  'context.deletePermanent': 'Eliminar permanentemente',
  'context.emptyRecycle': 'Vaciar Papelera de reciclaje',
  'context.properties': 'Propiedades',
  'filesystem.newFolder': 'Nueva carpeta',
  'filesystem.newText': 'Nuevo documento de texto.txt',
  'filesystem.folder': 'Carpeta de archivos',
  'filesystem.text': 'Documento de texto',
  'filesystem.desktop': 'Escritorio',
  'filesystem.workExperience': 'Experiencia laboral',
  'filesystem.recycleBin': 'Papelera de reciclaje',
  'dialog.renameTitle': 'Cambiar nombre',
  'dialog.renameLabel': 'Escribe un nombre nuevo:',
  'dialog.save': 'Aceptar',
  'dialog.cancel': 'Cancelar',
  'dialog.propertiesTitle': 'Propiedades',
  'dialog.type': 'Tipo:',
  'dialog.location': 'Ubicación:',
  'dialog.created': 'Creado:',
  'dialog.modified': 'Modificado:',
  'dialog.size': 'Tamaño:',
  'dialog.items': 'Elementos:',
  'dialog.characters': '{{count}} caracteres',
  'dialog.close': 'Cerrar',
  'dialog.deleteTitle': 'Confirmar eliminación',
  'dialog.deleteMessage': '¿Quieres mover los elementos seleccionados a la Papelera de reciclaje?',
  'dialog.permanentDeleteTitle': 'Eliminar permanentemente',
  'dialog.permanentDeleteMessage': 'Esta acción eliminará definitivamente los elementos seleccionados hasta que se reinicie el equipo.',
  'dialog.emptyRecycleTitle': 'Vaciar Papelera de reciclaje',
  'dialog.emptyRecycleMessage': '¿Quieres eliminar definitivamente todo el contenido de la Papelera?',
  'dialog.confirm': 'Sí',
  'dialog.no': 'No',
  'notepad.workPath': 'C:\\Portafolio\\Experiencia laboral',
  'notepad.context': 'CONTEXTO',
  'notepad.responsibilities': 'RESPONSABILIDADES',
  'notepad.technologies': 'TECNOLOGÍAS UTILIZADAS',
  'notepad.competencies': 'COMPETENCIAS DEMOSTRADAS',
  'notepad.editorLabel': 'Editor de {{name}}',
  'notepad.editableStatus': 'Editable · Los cambios se conservarán hasta reiniciar el equipo.',
  'filesystem.image': 'Imagen',
  'filesystem.audio': 'Archivo de audio M4A',
  'image.menu': 'Menú del visor de imágenes',
  'image.alt': 'Imagen {{name}}',
  'image.previous': 'Imagen anterior',
  'image.next': 'Imagen siguiente',
  'education.path': 'C:\\Portafolio\\Formación.txt',
  'education.education': 'FORMACIÓN',
  'education.languages': 'IDIOMAS',
  'pdf.download': 'Descargar',
  'pdf.iframeTitle': 'Currículum de Daniel Ramón Pérez',
  'pdf.fallbackStart': 'Si el navegador no muestra el visor,',
  'pdf.openNewTab': 'abre el PDF en una pestaña nueva',
  'terminal.label': 'Terminal del portfolio',
  'terminal.version': 'Portfolio [Versión 1.0]',
  'terminal.copyright': '(c) Daniel Ramón Pérez. Terminal del portfolio.',
  'terminal.notice': 'Escribe help para ver los comandos disponibles.',
  'terminal.inputLabel': 'Línea de comandos de Terminal',
  'hire.formLabel': 'Formulario para enviar una oferta de trabajo',
  'hire.heading': 'Contratar a Daniel',
  'hire.introduction': 'Cuéntame brevemente qué tenéis entre manos.',
  'hire.company': 'Empresa',
  'hire.companyPlaceholder': 'Acme Software',
  'hire.position': '¿De qué trata la posición?',
  'hire.positionPlaceholder': 'Cuéntame todo lo que consideres oportuno sobre la posición, el proyecto, el equipo, las tecnologías o cualquier otro detalle relevante.',
  'hire.workMode': 'Modalidad',
  'hire.selectPlaceholder': 'Selecciona una opción...',
  'hire.mode.remote': 'Remoto',
  'hire.mode.hybrid': 'Híbrido',
  'hire.mode.onSite': 'Presencial',
  'hire.mode.flexible': 'Flexible / Por definir',
  'hire.location': 'Ubicación',
  'hire.locationPlaceholder': 'Barcelona, España',
  'hire.contractType': 'Tipo de contrato',
  'hire.optionalSelect': 'Por definir',
  'hire.contract.permanent': 'Indefinido',
  'hire.contract.temporary': 'Temporal',
  'hire.contract.freelance': 'Freelance / Autónomo',
  'hire.contract.internship': 'Prácticas',
  'hire.contract.other': 'Otro',
  'hire.contract.undefined': 'Por definir',
  'hire.salary': 'Rango salarial',
  'hire.salaryPlaceholder': 'Ej. 35–40k € brutos/año',
  'hire.jobUrl': 'Enlace a la oferta',
  'hire.jobUrlPlaceholder': 'https://...',
  'hire.contactName': 'Nombre de contacto',
  'hire.contactNamePlaceholder': 'Laura García',
  'hire.contactEmail': 'Email de contacto',
  'hire.contactEmailPlaceholder': 'laura@acme.com',
  'hire.additional': 'Algo más que quieras contarme',
  'hire.additionalPlaceholder': 'Cualquier detalle adicional...',
  'hire.privacy': 'Los datos introducidos se utilizarán únicamente para responder a esta oferta y no se almacenarán en el portfolio.',
  'hire.submit': 'Enviar oferta',
  'hire.sending': 'Enviando...',
  'hire.validation.required': 'Este campo es obligatorio.',
  'hire.validation.email': 'Introduce un email válido.',
  'hire.validation.url': 'Introduce una URL válida que empiece por http:// o https://.',
  'hire.validation.maxLength': 'Utiliza como máximo {{count}} caracteres.',
  'hire.successTitle': 'Oferta enviada',
  'hire.successMessage': '¡Gracias! Tu oferta ha sido enviada correctamente.',
  'hire.errorTitle': 'No se ha podido enviar el mensaje.',
  'hire.errorMessage': 'Puedes intentarlo de nuevo o contactar conmigo directamente:',
  'hire.accept': 'Aceptar',
  'paint.menu.label': 'Menús de Paint 98',
  'paint.menu.file': 'Archivo',
  'paint.menu.edit': 'Edición',
  'paint.menu.view': 'Ver',
  'paint.menu.image': 'Imagen',
  'paint.menu.colors': 'Colores',
  'paint.menu.help': 'Ayuda',
  'paint.file.new': 'Nuevo',
  'paint.file.open': 'Abrir...',
  'paint.file.save': 'Guardar',
  'paint.file.saveAs': 'Guardar como...',
  'paint.file.exportPng': 'Exportar como PNG...',
  'paint.file.exit': 'Salir',
  'paint.edit.undo': 'Deshacer',
  'paint.edit.redo': 'Rehacer',
  'paint.edit.clear': 'Limpiar lienzo',
  'paint.view.toolbox': 'Cuadro de herramientas',
  'paint.view.palette': 'Paleta de colores',
  'paint.view.status': 'Barra de estado',
  'paint.image.clear': 'Borrar imagen',
  'paint.image.invert': 'Invertir colores',
  'paint.colors.reset': 'Restablecer colores',
  'paint.colors.palette': 'Paleta de colores de Paint 98',
  'paint.colors.current': 'Color actual y color de fondo',
  'paint.colors.select': 'Seleccionar color {{color}}',
  'paint.help.about': 'Acerca de Paint 98',
  'paint.help.description': 'Paint 98\nUna pequeña aplicación de dibujo integrada en el portfolio de Daniel.',
  'paint.tools.label': 'Herramientas de dibujo',
  'paint.tool.pencil': 'Lápiz',
  'paint.tool.brush': 'Pincel',
  'paint.tool.eraser': 'Borrador',
  'paint.tool.fill': 'Relleno con color',
  'paint.tool.line': 'Línea',
  'paint.tool.rectangle': 'Rectángulo',
  'paint.tool.ellipse': 'Elipse',
  'paint.width.label': 'Grosor del trazo',
  'paint.width.option': 'Trazo de {{width}} píxeles',
  'paint.canvas.label': 'Lienzo de Paint 98',
  'paint.status.tool': 'Herramienta',
  'paint.dialog.saveAsTitle': 'Guardar como',
  'paint.dialog.fileName': 'Nombre del archivo:',
  'paint.dialog.newTitle': 'Paint 98',
  'paint.dialog.discard': 'La imagen ha cambiado. ¿Quieres descartarla y crear una nueva?',
  'paint.dialog.yes': 'Sí',
  'paint.dialog.no': 'No',
  'paint.dialog.ok': 'Aceptar',
  'paint.dialog.cancel': 'Cancelar',
  'paint.error.title': 'Paint 98',
  'paint.error.canvas': 'No se ha podido preparar el lienzo en este navegador.',
  'paint.error.open': 'No se pudo abrir la imagen seleccionada.',
  'paint.error.save': 'No se pudo exportar la imagen.',
  'solitaire.menu.label': 'Menús de Solitario',
  'solitaire.menu.game': 'Juego',
  'solitaire.menu.help': 'Ayuda',
  'solitaire.game.new': 'Nuevo juego',
  'solitaire.game.undo': 'Deshacer',
  'solitaire.game.exit': 'Salir',
  'solitaire.help.rules': 'Cómo jugar',
  'solitaire.help.about': 'Acerca de Solitario',
  'solitaire.help.rulesText': 'Mueve las cartas en orden descendente alternando rojo y negro. Solo los reyes pueden ocupar una columna vacía. Completa las cuatro bases por palo, desde el as hasta el rey. Haz doble clic en una carta para enviarla a su base cuando sea posible.',
  'solitaire.help.aboutText': 'Solitario\nEdición Portfolio: una versión jugable del clásico Klondike integrada en este escritorio.',
  'solitaire.stock.draw': 'Robar una carta del mazo',
  'solitaire.stock.redeal': 'Volver a repartir el descarte',
  'solitaire.waste': 'Descarte',
  'solitaire.foundation.label': 'Base de {{suit}}',
  'solitaire.tableau': 'Columnas del solitario',
  'solitaire.tableauColumn': 'Columna {{column}}',
  'solitaire.instructions': 'Haz clic o arrastra las cartas. Doble clic para enviarlas a las bases.',
  'solitaire.status.moves': 'Movimientos: {{moves}}',
  'solitaire.status.stock': 'Mazo: {{cards}}',
  'solitaire.card.label': '{{rank}} de {{suit}}',
  'solitaire.card.faceDown': 'Carta boca abajo',
  'solitaire.suit.clubs': 'tréboles',
  'solitaire.suit.diamonds': 'diamantes',
  'solitaire.suit.hearts': 'corazones',
  'solitaire.suit.spades': 'picas',
  'solitaire.dialog.ok': 'Aceptar',
  'solitaire.win.title': '¡Partida completada!',
  'solitaire.win.message': 'Has resuelto el solitario en {{moves}} movimientos.',
  'solitaire.win.playAgain': 'Jugar otra vez',
  'minesweeper.menu.label': 'Menús de Buscaminas',
  'minesweeper.menu.game': 'Juego',
  'minesweeper.menu.help': 'Ayuda',
  'minesweeper.game.new': 'Nueva partida',
  'minesweeper.game.exit': 'Salir',
  'minesweeper.difficulty.beginner': 'Principiante',
  'minesweeper.difficulty.intermediate': 'Intermedio',
  'minesweeper.difficulty.expert': 'Experto',
  'minesweeper.help.rules': 'Cómo jugar',
  'minesweeper.help.about': 'Acerca de Buscaminas',
  'minesweeper.help.rulesText': 'Descubre todas las casillas que no contienen minas. Los números indican cuántas minas hay alrededor. Haz clic derecho para colocar una bandera o activa el modo bandera en pantallas táctiles. El primer clic siempre es seguro.',
  'minesweeper.help.aboutText': 'Buscaminas\nEdición Portfolio: el clásico juego de lógica integrado en este escritorio.',
  'minesweeper.status.label': 'Marcador de Buscaminas',
  'minesweeper.status.remaining': 'Minas restantes',
  'minesweeper.status.time': 'Tiempo transcurrido',
  'minesweeper.status.ready': 'Listo para empezar.',
  'minesweeper.status.playing': 'Partida en curso.',
  'minesweeper.status.won': '¡Has despejado el campo!',
  'minesweeper.status.lost': 'Has encontrado una mina.',
  'minesweeper.flagMode': 'Modo bandera',
  'minesweeper.board.label': 'Campo de minas',
  'minesweeper.cell.hidden': 'Casilla oculta, fila {{row}}, columna {{column}}',
  'minesweeper.cell.flagged': 'Casilla marcada, fila {{row}}, columna {{column}}',
  'minesweeper.cell.mine': 'Mina',
  'minesweeper.cell.revealed': 'Casilla descubierta, fila {{row}}, columna {{column}}, {{mines}} minas cercanas',
  'minesweeper.mines': 'minas',
  'minesweeper.dialog.ok': 'Aceptar',
  'messageBoard.menu.label': 'Menús del Message Board',
  'messageBoard.menu.exit': 'Salir',
  'messageBoard.menu.refresh': 'Actualizar',
  'messageBoard.menu.about': 'Acerca de Message Board',
  'messageBoard.tableLabel': 'Conversación pública',
  'messageBoard.author': 'Autor',
  'messageBoard.message': 'Mensaje',
  'messageBoard.loading': 'Consultando mensajes...',
  'messageBoard.unavailable': 'El tablón no está disponible en este momento.',
  'messageBoard.administrator': 'Administrador',
  'messageBoard.visitor': 'Visitante',
  'messageBoard.name': 'Nombre:',
  'messageBoard.messageLabel': 'Mensaje:',
  'messageBoard.formLabel': 'Publicar un mensaje en el tablón',
  'messageBoard.publish': 'Publicar mensaje',
  'messageBoard.posting': 'Publicando...',
  'messageBoard.postError': 'No se pudo publicar. Inténtalo de nuevo dentro de unos minutos.',
  'messageBoard.delete': 'Eliminar mensaje',
  'messageBoard.deleteTitle': 'Eliminar mensaje',
  'messageBoard.deleteConfirm': '¿Quieres eliminar permanentemente el mensaje #{{id}}?',
  'messageBoard.deleting': 'Eliminando...',
  'messageBoard.deleteErrorTitle': 'No se pudo eliminar',
  'messageBoard.deleteError': 'La sesión de administrador no es válida o el servidor no está disponible.',
  'messageBoard.validation.required': 'Este campo es obligatorio.',
  'messageBoard.validation.maxLength': 'Utiliza como máximo {{count}} caracteres.',
  'messageBoard.pagination': 'Páginas de mensajes',
  'messageBoard.older': 'Más antiguos',
  'messageBoard.newer': 'Más recientes',
  'messageBoard.page': 'Página {{current}} de {{total}}',
  'messageBoard.adminMessage': '¡Bienvenido al Message Board! Aquí puedes dejar un mensaje, compartir ideas y comentar sobre proyectos. ¡Gracias por pasarte!',
  'messageBoard.aboutText': 'Un tablón público inspirado en los guestbooks de finales de los 90.',
  'taskManager.tabs': 'Secciones del Administrador de tareas',
  'taskManager.tab.applications': 'Aplicaciones',
  'taskManager.tab.processes': 'Procesos',
  'taskManager.tab.map': 'Mapa y actividad',
  'taskManager.tab.performance': 'Rendimiento',
  'taskManager.task': 'Tarea',
  'taskManager.state': 'Estado',
  'taskManager.process': 'Proceso',
  'taskManager.kind': 'Tipo',
  'taskManager.system': 'Sistema',
  'taskManager.application': 'Aplicación',
  'taskManager.noApplications': 'No hay aplicaciones abiertas.',
  'taskManager.switchTo': 'Cambiar a',
  'taskManager.endTask': 'Finalizar tarea',
  'taskManager.processesNote': 'Procesos virtuales de DRP OS. No se inspeccionan procesos ni recursos del dispositivo del visitante.',
  'taskManager.mapLabel': 'Topología en vivo de DRP OS',
  'taskManager.database': 'Base de datos',
  'taskManager.localSession': 'Sesión local',
  'taskManager.systemState': 'Estado del sistema',
  'taskManager.generalState': 'Estado general:',
  'taskManager.activeApps': 'Apps activas:',
  'taskManager.activeRequests': 'Requests activas:',
  'taskManager.errors': 'Requests con error:',
  'taskManager.averageLatency': 'Latencia media:',
  'taskManager.totalRequests': 'Requests totales:',
  'taskManager.upload': 'Tráfico de subida:',
  'taskManager.download': 'Tráfico de bajada:',
  'taskManager.sessionMetrics': 'Métricas de la sesión',
  'taskManager.recentActivity': 'Latencia reciente',
  'taskManager.latencyChart': 'Gráfico de latencia de peticiones recientes',
  'taskManager.operation': 'Operación',
  'taskManager.source': 'Origen',
  'taskManager.latency': 'Latencia',
  'taskManager.noActivity': 'Aún no hay actividad de red.',
  'taskManager.metricsNote': 'Datos medidos únicamente dentro de esta sesión de DRP OS; no representan CPU, memoria ni red total del equipo.',
  'taskManager.statusbar': 'Monitor de actividad de la sesión',
  'taskManager.status.online': 'Online',
  'taskManager.status.processing': 'Procesando',
  'taskManager.status.error': 'Error',
  'taskManager.status.unknown': 'Sin comprobar',
  'taskManager.general.online': 'Online',
  'taskManager.general.processing': 'Procesando',
  'taskManager.general.degraded': 'Degradado',
  'taskManager.window.active': 'Activa',
  'taskManager.window.running': 'En ejecución',
  'taskManager.window.minimized': 'Minimizada',
  'recycle.address': 'Dirección',
  'recycle.path': 'C:\\Papelera de reciclaje',
  'recycle.empty': 'La Papelera de reciclaje está vacía.',
  'recycle.restoreSelected': 'Restaurar seleccionados',
  'recycle.contents': 'Contenido de la Papelera de reciclaje',
  'recycle.emptyAction': 'Vaciar Papelera',
  'source.title': 'URL del código fuente sin configurar',
  'source.description': 'Este espacio de trabajo no tiene un repositorio Git ni un remoto público, por lo que el portfolio no inventará una URL de GitHub.',
  'source.path': 'Configura SOURCE_CODE_URL en desktop/config/source-code.config.ts.',
} as const;

export type ClaveTraduccion = keyof typeof TEXTOS_ESPANOL;

const TEXTOS_INGLES: Record<ClaveTraduccion, string> = {
  'app.loadingLabel': 'Loading portfolio',
  'app.loadingProfile': 'Loading professional profile...',
  'app.errorTitle': 'Unable to load profile data.',
  'app.errorDescription': 'Check that the API is available and try again.',
  'app.retry': 'Retry',
  'shell.portfolioLabel': 'Daniel Ramón Pérez interactive portfolio',
  'shell.desktopLabel': "Daniel's desktop",
  'shell.applicationsLabel': 'Desktop applications',
  'action.open': 'Open',
  'action.openNewTab': 'Open {{name}} in a new tab',
  'action.minimize': 'Minimize {{name}}',
  'action.maximize': 'Maximize {{name}}',
  'action.restore': 'Restore {{name}}',
  'action.close': 'Close {{name}}',
  'taskbar.label': 'Taskbar',
  'taskbar.start': 'Start',
  'taskbar.openApplications': 'Open applications',
  'taskbar.localTime': 'Local time',
  'taskbar.languageSelector': 'Select language',
  'taskbar.spanish': 'Spanish',
  'taskbar.english': 'English',
  'startMenu.label': 'Start menu',
  'startMenu.reset': 'Reset desktop layout',
  'startMenu.restart': 'Restart computer',
  'restart.status': 'The computer is restarting',
  'restart.title': 'Restarting',
  'restart.shuttingDown': 'Closing applications...',
  'restart.booting': 'Restoring the desktop...',
  'restart.systemMessage': 'MEMORY OK · FILES OK · RESTORING SESSION',
  'application.about.label': 'About me',
  'application.about.title': 'About me',
  'application.work.label': 'Work Experience',
  'application.work.title': 'Work Experience',
  'application.linkedin.label': 'LinkedIn',
  'application.linkedin.title': 'LinkedIn',
  'application.education.label': 'Education.txt',
  'application.education.title': 'Education.txt - Notepad',
  'application.source.label': 'Source Code',
  'application.source.title': 'Source Code',
  'application.pdf.label': 'Daniel_Ramon_Perez_CV.pdf',
  'application.pdf.title': 'Daniel_Ramon_Perez_CV.pdf - Viewer',
  'application.terminal.label': 'Terminal.exe',
  'application.terminal.title': 'Terminal.exe',
  'application.hire.label': 'Hire me',
  'application.hire.title': 'Send a job offer',
  'application.paint.label': 'Paint 98',
  'application.paint.title': 'untitled - Paint 98',
  'application.solitaire.label': 'Solitaire',
  'application.solitaire.title': 'Solitaire',
  'application.minesweeper.label': 'Minesweeper',
  'application.minesweeper.title': 'Minesweeper',
  'application.messageBoard.label': 'Message Board',
  'application.messageBoard.title': 'Message Board',
  'application.taskManager.label': 'Task Manager',
  'application.taskManager.title': 'Task Manager',
  'application.drpExplorer.label': 'DRP Explorer',
  'application.drpExplorer.title': 'DRP Explorer',
  'application.audioPlayer.label': 'Player',
  'application.audioPlayer.title': 'Player',
  'application.music.label': 'Music',
  'application.music.title': 'Music',
  'application.photoAlbum.label': 'Photo Album',
  'application.photoAlbum.title': 'Photo Album',
  'application.recycle.label': 'Recycle Bin',
  'application.recycle.title': 'Recycle Bin',
  'application.welcome.label': 'Welcome',
  'application.welcome.title': 'Welcome',
  'application.experience.label': 'Experience',
  'application.sourceMessage.title': 'Information',
  'window.notepad': 'Notepad',
  'window.imageViewer': 'Image Viewer',
  'welcome.eyebrow': 'Welcome',
  'welcome.presentationIntro': "Hi! I'm Dani Ramón Pérez, a Full-Stack Developer with over 3 years of experience.",
  'welcome.presentationExplore': 'This CV was made to be explored: open folders, move things around and look through it until you find what you want to know about me.',
  'welcome.presentationMess': 'If you leave the desktop in a mess, no problem: you can',
  'welcome.presentationRestart': 'restart the system from Start',
  'welcome.mainTechnologies': 'Main technologies',
  'welcome.quickAccess': 'Quick access',
  'welcome.work': 'Work Experience',
  'welcome.about': 'About me',
  'welcome.viewCv': 'View CV',
  'welcome.source': 'Source Code',
  'welcome.hint': 'Tip: select an icon and press Enter, or double-click it to open.',
  'welcome.restApis': 'REST APIs',
  'about.tabsLabel': 'Profile properties',
  'about.tab.general': 'General',
  'about.tab.profile': 'Profile',
  'about.tab.technologies': 'Technologies',
  'about.tab.contact': 'Contact',
  'about.portraitAlt': 'Pixel-art portrait of Daniel Ramón Pérez',
  'about.systemInformation': 'System information',
  'about.mainFrontend': 'Main frontend:',
  'about.mainBackend': 'Main backend:',
  'about.database': 'Database:',
  'about.otherTechnologies': 'Other technologies:',
  'about.language': 'Language:',
  'about.specialty': 'Specialty:',
  'about.specialtyText': 'Web applications and management systems, healthcare software, ERP, REST APIs and business logic.',
  'about.professionalProfile': 'Professional profile',
  'about.demonstratedCompetencies': 'Demonstrated competencies',
  'about.cvTechnologies': 'CV technologies',
  'about.explicitTechnologies': 'This list contains only technologies explicitly mentioned in the CV.',
  'about.group.frontend': 'Frontend and web languages',
  'about.group.backend': 'Backend and languages',
  'about.group.database': 'Database',
  'about.group.other': 'Other tools',
  'about.contact': 'Contact',
  'about.location': 'Location',
  'about.email': 'Email',
  'about.phone': 'Phone',
  'about.openProfile': 'Open profile',
  'about.accept': 'OK',
  'about.apply': 'Apply',
  'menu.explorer': 'Explorer menu',
  'menu.notepad': 'Notepad menu',
  'menu.file': 'File',
  'file.download': 'Download...',
  'menu.edit': 'Edit',
  'menu.view': 'View',
  'menu.help': 'Help',
  'menu.search': 'Search',
  'explorer.back': 'Back',
  'explorer.address': 'Address',
  'explorer.workPath': 'C:\\Portfolio\\Work Experience',
  'explorer.professionalFiles': 'Professional experience files',
  'explorer.addedItems': 'Items added to this folder',
  'explorer.moveToDesktop': 'Move to desktop',
  'explorer.objects': '{{count}} object(s)',
  'explorer.folderContents': 'Folder contents',
  'notepad.persistedStatus': 'Editable · Changes survive reloads and are removed when the computer restarts.',
  'context.new': 'New',
  'context.newFolder': 'Folder',
  'context.newText': 'Text document',
  'context.sort': 'Arrange icons',
  'context.sortName': 'By name',
  'context.sortType': 'By type',
  'context.sortCreated': 'By creation date',
  'context.sortOriginal': 'Original order',
  'context.align': 'Align icons',
  'context.refresh': 'Refresh',
  'context.open': 'Open',
  'context.edit': 'Edit',
  'context.cut': 'Cut',
  'context.copy': 'Copy',
  'context.paste': 'Paste',
  'context.rename': 'Rename',
  'context.sendTo': 'Send to',
  'context.sendDesktop': 'Desktop',
  'context.sendWork': 'Work Experience',
  'context.sendMusic': 'Music',
  'context.sendRecycle': 'Recycle Bin',
  'context.delete': 'Delete',
  'context.restore': 'Restore',
  'context.deletePermanent': 'Delete permanently',
  'context.emptyRecycle': 'Empty Recycle Bin',
  'context.properties': 'Properties',
  'filesystem.newFolder': 'New folder',
  'filesystem.newText': 'New text document.txt',
  'filesystem.folder': 'File folder',
  'filesystem.text': 'Text document',
  'filesystem.desktop': 'Desktop',
  'filesystem.workExperience': 'Work Experience',
  'filesystem.recycleBin': 'Recycle Bin',
  'dialog.renameTitle': 'Rename',
  'dialog.renameLabel': 'Type a new name:',
  'dialog.save': 'OK',
  'dialog.cancel': 'Cancel',
  'dialog.propertiesTitle': 'Properties',
  'dialog.type': 'Type:',
  'dialog.location': 'Location:',
  'dialog.created': 'Created:',
  'dialog.modified': 'Modified:',
  'dialog.size': 'Size:',
  'dialog.items': 'Items:',
  'dialog.characters': '{{count}} characters',
  'dialog.close': 'Close',
  'dialog.deleteTitle': 'Confirm delete',
  'dialog.deleteMessage': 'Do you want to move the selected items to the Recycle Bin?',
  'dialog.permanentDeleteTitle': 'Delete permanently',
  'dialog.permanentDeleteMessage': 'This action will permanently remove the selected items until the computer restarts.',
  'dialog.emptyRecycleTitle': 'Empty Recycle Bin',
  'dialog.emptyRecycleMessage': 'Do you want to permanently delete everything in the Recycle Bin?',
  'dialog.confirm': 'Yes',
  'dialog.no': 'No',
  'notepad.workPath': 'C:\\Portfolio\\Work Experience',
  'notepad.context': 'CONTEXT',
  'notepad.responsibilities': 'RESPONSIBILITIES',
  'notepad.technologies': 'TECHNOLOGIES USED',
  'notepad.competencies': 'DEMONSTRATED COMPETENCIES',
  'notepad.editorLabel': '{{name}} editor',
  'notepad.editableStatus': 'Editable · Changes will be kept until the computer restarts.',
  'filesystem.image': 'Image',
  'filesystem.audio': 'M4A audio file',
  'image.menu': 'Image viewer menu',
  'image.alt': '{{name}} image',
  'image.previous': 'Previous image',
  'image.next': 'Next image',
  'education.path': 'C:\\Portfolio\\Education.txt',
  'education.education': 'EDUCATION',
  'education.languages': 'LANGUAGES',
  'pdf.download': 'Download',
  'pdf.iframeTitle': 'Curriculum vitae of Daniel Ramón Pérez',
  'pdf.fallbackStart': 'If the browser does not display the viewer,',
  'pdf.openNewTab': 'open the PDF in a new tab',
  'terminal.label': 'Portfolio terminal',
  'terminal.version': 'Portfolio [Version 1.0]',
  'terminal.copyright': '(c) Daniel Ramón Pérez. Portfolio terminal.',
  'terminal.notice': 'Type help to see the available commands.',
  'terminal.inputLabel': 'Terminal command line',
  'hire.formLabel': 'Job offer submission form',
  'hire.heading': 'Hire Daniel',
  'hire.introduction': "Tell me briefly what you're working on.",
  'hire.company': 'Company',
  'hire.companyPlaceholder': 'Acme Software',
  'hire.position': 'What is the position about?',
  'hire.positionPlaceholder': 'Tell me anything you consider relevant about the position, project, team, technologies or any other useful detail.',
  'hire.workMode': 'Work mode',
  'hire.selectPlaceholder': 'Select an option...',
  'hire.mode.remote': 'Remote',
  'hire.mode.hybrid': 'Hybrid',
  'hire.mode.onSite': 'On-site',
  'hire.mode.flexible': 'Flexible / To be defined',
  'hire.location': 'Location',
  'hire.locationPlaceholder': 'Barcelona, Spain',
  'hire.contractType': 'Contract type',
  'hire.optionalSelect': 'To be defined',
  'hire.contract.permanent': 'Permanent',
  'hire.contract.temporary': 'Temporary',
  'hire.contract.freelance': 'Freelance / Self-employed',
  'hire.contract.internship': 'Internship',
  'hire.contract.other': 'Other',
  'hire.contract.undefined': 'To be defined',
  'hire.salary': 'Salary range',
  'hire.salaryPlaceholder': 'E.g. €35–40k gross/year',
  'hire.jobUrl': 'Job posting link',
  'hire.jobUrlPlaceholder': 'https://...',
  'hire.contactName': 'Contact name',
  'hire.contactNamePlaceholder': 'Laura García',
  'hire.contactEmail': 'Contact email',
  'hire.contactEmailPlaceholder': 'laura@acme.com',
  'hire.additional': 'Anything else you would like to tell me?',
  'hire.additionalPlaceholder': 'Any additional details...',
  'hire.privacy': 'The information entered will only be used to respond to this offer and will not be stored by the portfolio.',
  'hire.submit': 'Send offer',
  'hire.sending': 'Sending...',
  'hire.validation.required': 'This field is required.',
  'hire.validation.email': 'Enter a valid email address.',
  'hire.validation.url': 'Enter a valid URL beginning with http:// or https://.',
  'hire.validation.maxLength': 'Use no more than {{count}} characters.',
  'hire.successTitle': 'Offer sent',
  'hire.successMessage': 'Thank you! Your offer has been sent successfully.',
  'hire.errorTitle': 'The message could not be sent.',
  'hire.errorMessage': 'You can try again or contact me directly:',
  'hire.accept': 'OK',
  'paint.menu.label': 'Paint 98 menus',
  'paint.menu.file': 'File',
  'paint.menu.edit': 'Edit',
  'paint.menu.view': 'View',
  'paint.menu.image': 'Image',
  'paint.menu.colors': 'Colors',
  'paint.menu.help': 'Help',
  'paint.file.new': 'New',
  'paint.file.open': 'Open...',
  'paint.file.save': 'Save',
  'paint.file.saveAs': 'Save As...',
  'paint.file.exportPng': 'Export as PNG...',
  'paint.file.exit': 'Exit',
  'paint.edit.undo': 'Undo',
  'paint.edit.redo': 'Redo',
  'paint.edit.clear': 'Clear canvas',
  'paint.view.toolbox': 'Tool Box',
  'paint.view.palette': 'Color Box',
  'paint.view.status': 'Status Bar',
  'paint.image.clear': 'Clear Image',
  'paint.image.invert': 'Invert Colors',
  'paint.colors.reset': 'Reset Colors',
  'paint.colors.palette': 'Paint 98 color palette',
  'paint.colors.current': 'Current foreground and background colors',
  'paint.colors.select': 'Select color {{color}}',
  'paint.help.about': 'About Paint 98',
  'paint.help.description': "Paint 98\nA small drawing application built into Daniel's portfolio.",
  'paint.tools.label': 'Drawing tools',
  'paint.tool.pencil': 'Pencil',
  'paint.tool.brush': 'Brush',
  'paint.tool.eraser': 'Eraser',
  'paint.tool.fill': 'Fill With Color',
  'paint.tool.line': 'Line',
  'paint.tool.rectangle': 'Rectangle',
  'paint.tool.ellipse': 'Ellipse',
  'paint.width.label': 'Stroke width',
  'paint.width.option': '{{width}} pixel stroke',
  'paint.canvas.label': 'Paint 98 drawing canvas',
  'paint.status.tool': 'Tool',
  'paint.dialog.saveAsTitle': 'Save As',
  'paint.dialog.fileName': 'File name:',
  'paint.dialog.newTitle': 'Paint 98',
  'paint.dialog.discard': 'The image has changed. Discard it and create a new one?',
  'paint.dialog.yes': 'Yes',
  'paint.dialog.no': 'No',
  'paint.dialog.ok': 'OK',
  'paint.dialog.cancel': 'Cancel',
  'paint.error.title': 'Paint 98',
  'paint.error.canvas': 'The drawing canvas could not be prepared in this browser.',
  'paint.error.open': 'The selected image could not be opened.',
  'paint.error.save': 'The image could not be exported.',
  'solitaire.menu.label': 'Solitaire menus',
  'solitaire.menu.game': 'Game',
  'solitaire.menu.help': 'Help',
  'solitaire.game.new': 'New Game',
  'solitaire.game.undo': 'Undo',
  'solitaire.game.exit': 'Exit',
  'solitaire.help.rules': 'How to Play',
  'solitaire.help.about': 'About Solitaire',
  'solitaire.help.rulesText': 'Build tableau piles downward by alternating red and black cards. Only kings can fill an empty column. Complete all four foundations by suit, from ace to king. Double-click a card to send it to its foundation when possible.',
  'solitaire.help.aboutText': "Solitaire\nPortfolio Edition: a playable version of classic Klondike built into this desktop.",
  'solitaire.stock.draw': 'Draw a card from the stock',
  'solitaire.stock.redeal': 'Redeal the waste pile',
  'solitaire.waste': 'Waste pile',
  'solitaire.foundation.label': '{{suit}} foundation',
  'solitaire.tableau': 'Solitaire tableau',
  'solitaire.tableauColumn': 'Column {{column}}',
  'solitaire.instructions': 'Click or drag cards. Double-click to send a card to its foundation.',
  'solitaire.status.moves': 'Moves: {{moves}}',
  'solitaire.status.stock': 'Stock: {{cards}}',
  'solitaire.card.label': '{{rank}} of {{suit}}',
  'solitaire.card.faceDown': 'Face-down card',
  'solitaire.suit.clubs': 'clubs',
  'solitaire.suit.diamonds': 'diamonds',
  'solitaire.suit.hearts': 'hearts',
  'solitaire.suit.spades': 'spades',
  'solitaire.dialog.ok': 'OK',
  'solitaire.win.title': 'Game complete!',
  'solitaire.win.message': 'You solved Solitaire in {{moves}} moves.',
  'solitaire.win.playAgain': 'Play again',
  'minesweeper.menu.label': 'Minesweeper menus',
  'minesweeper.menu.game': 'Game',
  'minesweeper.menu.help': 'Help',
  'minesweeper.game.new': 'New Game',
  'minesweeper.game.exit': 'Exit',
  'minesweeper.difficulty.beginner': 'Beginner',
  'minesweeper.difficulty.intermediate': 'Intermediate',
  'minesweeper.difficulty.expert': 'Expert',
  'minesweeper.help.rules': 'How to Play',
  'minesweeper.help.about': 'About Minesweeper',
  'minesweeper.help.rulesText': 'Reveal every square that does not contain a mine. Numbers show how many mines are nearby. Right-click to place a flag, or use flag mode on touch screens. The first click is always safe.',
  'minesweeper.help.aboutText': 'Minesweeper\nPortfolio Edition: the classic logic game built into this desktop.',
  'minesweeper.status.label': 'Minesweeper scoreboard',
  'minesweeper.status.remaining': 'Mines remaining',
  'minesweeper.status.time': 'Elapsed time',
  'minesweeper.status.ready': 'Ready to start.',
  'minesweeper.status.playing': 'Game in progress.',
  'minesweeper.status.won': 'You cleared the minefield!',
  'minesweeper.status.lost': 'You found a mine.',
  'minesweeper.flagMode': 'Flag mode',
  'minesweeper.board.label': 'Minefield',
  'minesweeper.cell.hidden': 'Hidden square, row {{row}}, column {{column}}',
  'minesweeper.cell.flagged': 'Flagged square, row {{row}}, column {{column}}',
  'minesweeper.cell.mine': 'Mine',
  'minesweeper.cell.revealed': 'Revealed square, row {{row}}, column {{column}}, {{mines}} adjacent mines',
  'minesweeper.mines': 'mines',
  'minesweeper.dialog.ok': 'OK',
  'messageBoard.menu.label': 'Message Board menus',
  'messageBoard.menu.exit': 'Exit',
  'messageBoard.menu.refresh': 'Refresh',
  'messageBoard.menu.about': 'About Message Board',
  'messageBoard.tableLabel': 'Public conversation',
  'messageBoard.author': 'Author',
  'messageBoard.message': 'Message',
  'messageBoard.loading': 'Loading messages...',
  'messageBoard.unavailable': 'The message board is currently unavailable.',
  'messageBoard.administrator': 'Administrator',
  'messageBoard.visitor': 'Visitor',
  'messageBoard.name': 'Name:',
  'messageBoard.messageLabel': 'Message:',
  'messageBoard.formLabel': 'Post a message to the board',
  'messageBoard.publish': 'Post message',
  'messageBoard.posting': 'Posting...',
  'messageBoard.postError': 'The message could not be posted. Please try again in a few minutes.',
  'messageBoard.delete': 'Delete message',
  'messageBoard.deleteTitle': 'Delete message',
  'messageBoard.deleteConfirm': 'Permanently delete message #{{id}}?',
  'messageBoard.deleting': 'Deleting...',
  'messageBoard.deleteErrorTitle': 'The message could not be deleted',
  'messageBoard.deleteError': 'The administrator session is invalid or the server is unavailable.',
  'messageBoard.validation.required': 'This field is required.',
  'messageBoard.validation.maxLength': 'Use no more than {{count}} characters.',
  'messageBoard.pagination': 'Message pages',
  'messageBoard.older': 'Older',
  'messageBoard.newer': 'Newer',
  'messageBoard.page': 'Page {{current}} of {{total}}',
  'messageBoard.adminMessage': 'Welcome to the Message Board! Leave a message, share an idea or comment on a project. Thanks for stopping by!',
  'messageBoard.aboutText': 'A public message board inspired by late-90s guestbooks.',
  'taskManager.tabs': 'Task Manager sections',
  'taskManager.tab.applications': 'Applications',
  'taskManager.tab.processes': 'Processes',
  'taskManager.tab.map': 'Map & activity',
  'taskManager.tab.performance': 'Performance',
  'taskManager.task': 'Task',
  'taskManager.state': 'Status',
  'taskManager.process': 'Process',
  'taskManager.kind': 'Type',
  'taskManager.system': 'System',
  'taskManager.application': 'Application',
  'taskManager.noApplications': 'There are no open applications.',
  'taskManager.switchTo': 'Switch To',
  'taskManager.endTask': 'End Task',
  'taskManager.processesNote': "DRP OS virtual processes. The visitor's device processes and resources are never inspected.",
  'taskManager.mapLabel': 'Live DRP OS topology',
  'taskManager.database': 'Database',
  'taskManager.localSession': 'Local Session',
  'taskManager.systemState': 'System status',
  'taskManager.generalState': 'Overall status:',
  'taskManager.activeApps': 'Active apps:',
  'taskManager.activeRequests': 'Active requests:',
  'taskManager.errors': 'Failed requests:',
  'taskManager.averageLatency': 'Average latency:',
  'taskManager.totalRequests': 'Total requests:',
  'taskManager.upload': 'Uploaded traffic:',
  'taskManager.download': 'Downloaded traffic:',
  'taskManager.sessionMetrics': 'Session metrics',
  'taskManager.recentActivity': 'Recent latency',
  'taskManager.latencyChart': 'Recent request latency chart',
  'taskManager.operation': 'Operation',
  'taskManager.source': 'Source',
  'taskManager.latency': 'Latency',
  'taskManager.noActivity': 'There is no network activity yet.',
  'taskManager.metricsNote': 'Measured only inside this DRP OS session; these values do not represent total device CPU, memory or network usage.',
  'taskManager.statusbar': 'Session activity monitor',
  'taskManager.status.online': 'Online',
  'taskManager.status.processing': 'Processing',
  'taskManager.status.error': 'Error',
  'taskManager.status.unknown': 'Unchecked',
  'taskManager.general.online': 'Online',
  'taskManager.general.processing': 'Processing',
  'taskManager.general.degraded': 'Degraded',
  'taskManager.window.active': 'Active',
  'taskManager.window.running': 'Running',
  'taskManager.window.minimized': 'Minimized',
  'recycle.address': 'Address',
  'recycle.path': 'C:\\Recycle Bin',
  'recycle.empty': 'Recycle Bin is empty.',
  'recycle.restoreSelected': 'Restore selected',
  'recycle.contents': 'Recycle Bin contents',
  'recycle.emptyAction': 'Empty Recycle Bin',
  'source.title': 'Source Code URL not configured',
  'source.description': 'This workspace has no Git repository or public remote, so the portfolio will not invent a GitHub URL.',
  'source.path': 'Configure SOURCE_CODE_URL in desktop/config/source-code.config.ts.',
};

const TRADUCCIONES: Record<Idioma, Record<ClaveTraduccion, string>> = {
  es: TEXTOS_ESPANOL,
  en: TEXTOS_INGLES,
};

const CLAVES_ETIQUETAS_APLICACIONES: Record<string, ClaveTraduccion> = {
  about: 'application.about.label',
  'work-experience': 'application.work.label',
  linkedin: 'application.linkedin.label',
  education: 'application.education.label',
  'source-code': 'application.source.label',
  'pdf-viewer': 'application.pdf.label',
  terminal: 'application.terminal.label',
  'job-offer': 'application.hire.label',
  paint: 'application.paint.label',
  solitaire: 'application.solitaire.label',
  minesweeper: 'application.minesweeper.label',
  'message-board': 'application.messageBoard.label',
  'task-manager': 'application.taskManager.label',
  'drp-explorer': 'application.drpExplorer.label',
  'audio-player': 'application.audioPlayer.label',
  'music-folder': 'application.music.label',
  'photo-album': 'application.photoAlbum.label',
  'recycle-bin': 'application.recycle.label',
  welcome: 'application.welcome.label',
  'experience-notepad': 'application.experience.label',
  'source-code-message': 'application.source.label',
};

const CLAVES_TITULOS_APLICACIONES: Record<string, ClaveTraduccion> = {
  about: 'application.about.title',
  'work-experience': 'application.work.title',
  linkedin: 'application.linkedin.title',
  education: 'application.education.title',
  'source-code': 'application.source.title',
  'pdf-viewer': 'application.pdf.title',
  terminal: 'application.terminal.title',
  'job-offer': 'application.hire.title',
  paint: 'application.paint.title',
  solitaire: 'application.solitaire.title',
  minesweeper: 'application.minesweeper.title',
  'message-board': 'application.messageBoard.title',
  'task-manager': 'application.taskManager.title',
  'drp-explorer': 'application.drpExplorer.title',
  'audio-player': 'application.audioPlayer.title',
  'music-folder': 'application.music.title',
  'photo-album': 'application.photoAlbum.title',
  'recycle-bin': 'application.recycle.title',
  welcome: 'application.welcome.title',
  'source-code-message': 'application.sourceMessage.title',
};

const TRADUCCIONES_CONTENIDO: Record<string, Record<Idioma, string>> = {
  'Full-Stack Developer': { es: 'Desarrollador Full-Stack', en: 'Full-Stack Developer' },
  'Backend Developer': { es: 'Desarrollador Backend', en: 'Backend Developer' },
  'Barcelona, España': { es: 'Barcelona, España', en: 'Barcelona, Spain' },
  'Desarrollador Full-Stack con más de 3 años de experiencia en aplicaciones web y sistemas de gestión, especializado en Angular/TypeScript y Java/Spring sobre SQL Server. Experiencia en aplicaciones hospitalarias, ERP y APIs REST, incluyendo desarrollo de funcionalidades, implementación de reglas y validaciones, resolución de incidencias y trabajo directo con clientes y equipos internacionales.': {
    es: 'Desarrollador Full-Stack con más de 3 años de experiencia en aplicaciones web y sistemas de gestión, especializado en Angular/TypeScript y Java/Spring sobre SQL Server. Experiencia en aplicaciones hospitalarias, ERP y APIs REST, incluyendo desarrollo de funcionalidades, implementación de reglas y validaciones, resolución de incidencias y trabajo directo con clientes y equipos internacionales.',
    en: 'Full-Stack Developer with over 3 years of experience in web applications and management systems, specializing in Angular/TypeScript and Java/Spring with SQL Server. Experience in healthcare applications, ERP systems and REST APIs, including feature development, implementation of rules and validations, issue resolution, and direct collaboration with clients and international teams.',
  },
  'Desarrollador Full-Stack con más de 3 años de experiencia.': {
    es: 'Desarrollador Full-Stack con más de 3 años de experiencia.',
    en: 'Full-Stack Developer with over 3 years of experience.',
  },
  'Software hospitalario y sistemas ERP en entornos de producción.': {
    es: 'Software hospitalario y sistemas ERP en entornos de producción.',
    en: 'Healthcare software and ERP systems in production environments.',
  },
  'Desarrollo de aplicaciones web de gestión hospitalaria con Angular y TypeScript, y servicios REST con Java/Spring sobre SQL Server.': {
    es: 'Desarrollo de aplicaciones web de gestión hospitalaria con Angular y TypeScript, y servicios REST con Java/Spring sobre SQL Server.',
    en: 'Development of hospital management web applications with Angular and TypeScript, and REST services with Java/Spring on SQL Server.',
  },
  'Diseño e implementación de módulos para administración de medicación, sesiones de quimioterapia, pacientes e impresión de pulseras/etiquetas.': {
    es: 'Diseño e implementación de módulos para administración de medicación, sesiones de quimioterapia, pacientes e impresión de pulseras/etiquetas.',
    en: 'Design and implementation of modules for medication administration, chemotherapy sessions, patient management, and wristband/label printing.',
  },
  'Implementación de lógica de dominio y seguridad: rangos de dosis, doble verificación, selección de línea/canal, pasos de protocolo y restricciones por usuario/rol.': {
    es: 'Implementación de lógica de dominio y seguridad: rangos de dosis, doble verificación, selección de línea/canal, pasos de protocolo y restricciones por usuario/rol.',
    en: 'Implementation of domain logic and security controls: dose ranges, double-verification workflows, line/channel selection, protocol steps, and user/role restrictions.',
  },
  'Desarrollo de aplicaciones ERP con WinDev para producción, stock y monitorización de maquinaria, además de soporte técnico directo a clientes.': {
    es: 'Desarrollo de aplicaciones ERP con WinDev para producción, stock y monitorización de maquinaria, además de soporte técnico directo a clientes.',
    en: 'Development of ERP applications with WinDev for production, stock control and machinery monitoring, as well as direct technical support for clients.',
  },
  'Backend para plataformas CRM de gestión comercial y procesos de venta.': {
    es: 'Backend para plataformas CRM de gestión comercial y procesos de venta.',
    en: 'Backend development for CRM platforms supporting commercial management and sales processes.',
  },
  'Desarrollo backend de aplicaciones CRM y microservicios con Java/Spring Boot: APIs REST para cuentas, contactos y oportunidades; búsqueda, filtrado y paginación.': {
    es: 'Desarrollo backend de aplicaciones CRM y microservicios con Java/Spring Boot: APIs REST para cuentas, contactos y oportunidades; búsqueda, filtrado y paginación.',
    en: 'Backend development of CRM applications and microservices with Java/Spring Boot: REST APIs for accounts, contacts and opportunities; search, filtering and pagination.',
  },
  'Optimización de arquitectura de datos y rendimiento de consultas en SQL Server.': {
    es: 'Optimización de arquitectura de datos y rendimiento de consultas en SQL Server.',
    en: 'Optimization of data architecture and SQL Server query performance.',
  },
  'Aplicaciones web de gestión': { es: 'Aplicaciones web de gestión', en: 'Management web applications' },
  'Servicios REST con Java y Spring': { es: 'Servicios REST con Java y Spring', en: 'REST services with Java and Spring' },
  Microservicios: { es: 'Microservicios', en: 'Microservices' },
  'Búsqueda, filtrado y paginación': { es: 'Búsqueda, filtrado y paginación', en: 'Search, filtering and pagination' },
  'Lógica de dominio y validaciones': { es: 'Lógica de dominio y validaciones', en: 'Domain logic and validations' },
  'Roles y restricciones de acceso': { es: 'Roles y restricciones de acceso', en: 'Roles and access restrictions' },
  'Procesos hospitalarios': { es: 'Procesos hospitalarios', en: 'Healthcare processes' },
  'Procesos ERP': { es: 'Procesos ERP', en: 'ERP processes' },
  'Diseño y rendimiento de datos': { es: 'Diseño y rendimiento de datos', en: 'Data design and performance' },
  'Soporte técnico a clientes': { es: 'Soporte técnico a clientes', en: 'Technical customer support' },
  'Trabajo en entornos de producción': { es: 'Trabajo en entornos de producción', en: 'Work in production environments' },
  'Colaboración con equipos internacionales': { es: 'Colaboración con equipos internacionales', en: 'Collaboration with international teams' },
  'Desarrollo de aplicaciones web de gestión hospitalaria con Angular y TypeScript.': {
    es: 'Desarrollo de aplicaciones web de gestión hospitalaria con Angular y TypeScript.',
    en: 'Development of hospital management web applications with Angular and TypeScript.',
  },
  'Desarrollo de servicios REST hospitalarios y APIs REST para plataformas CRM.': {
    es: 'Desarrollo de servicios REST hospitalarios y APIs REST para plataformas CRM.',
    en: 'Development of healthcare REST services and REST APIs for CRM platforms.',
  },
  'Desarrollo backend de aplicaciones CRM y microservicios con Java y Spring Boot.': {
    es: 'Desarrollo backend de aplicaciones CRM y microservicios con Java y Spring Boot.',
    en: 'Backend development of CRM applications and microservices with Java and Spring Boot.',
  },
  'Implementación de estas operaciones en APIs REST para cuentas, contactos y oportunidades.': {
    es: 'Implementación de estas operaciones en APIs REST para cuentas, contactos y oportunidades.',
    en: 'Implementation of these operations in REST APIs for accounts, contacts and opportunities.',
  },
  'Implementación de rangos de dosis, doble verificación, pasos de protocolo y otras reglas hospitalarias.': {
    es: 'Implementación de rangos de dosis, doble verificación, pasos de protocolo y otras reglas hospitalarias.',
    en: 'Implementation of dose ranges, double verification, protocol steps and other healthcare rules.',
  },
  'Implementación de restricciones por usuario y rol en software hospitalario.': {
    es: 'Implementación de restricciones por usuario y rol en software hospitalario.',
    en: 'Implementation of user and role restrictions in healthcare software.',
  },
  'Módulos de medicación, quimioterapia, pacientes e impresión de pulseras y etiquetas.': {
    es: 'Módulos de medicación, quimioterapia, pacientes e impresión de pulseras y etiquetas.',
    en: 'Medication, chemotherapy and patient modules, plus wristband and label printing.',
  },
  'Aplicaciones para producción, stock y monitorización de maquinaria.': {
    es: 'Aplicaciones para producción, stock y monitorización de maquinaria.',
    en: 'Applications for production, stock control and machinery monitoring.',
  },
  'Soporte técnico directo a clientes en aplicaciones ERP.': {
    es: 'Soporte técnico directo a clientes en aplicaciones ERP.',
    en: 'Direct technical support for clients using ERP applications.',
  },
  'Software hospitalario y sistemas ERP mantenidos en entornos de producción.': {
    es: 'Software hospitalario y sistemas ERP mantenidos en entornos de producción.',
    en: 'Healthcare software and ERP systems maintained in production environments.',
  },
  'El perfil profesional declara trabajo directo con clientes y equipos internacionales.': {
    es: 'El perfil profesional declara trabajo directo con clientes y equipos internacionales.',
    en: 'The professional profile states direct work with clients and international teams.',
  },
  'Grado en Ingeniería Informática': { es: 'Grado en Ingeniería Informática', en: "Bachelor's Degree in Computer Engineering" },
  'Técnico Superior DAM': { es: 'Técnico Superior DAM', en: 'Higher Technician in Multiplatform Application Development' },
  Inglés: { es: 'Inglés', en: 'English' },
  'Software hospitalario.': { es: 'Software hospitalario.', en: 'Healthcare software.' },
  'Desarrollo de aplicaciones web.': { es: 'Desarrollo de aplicaciones web.', en: 'Web application development.' },
  'Backend para plataformas CRM.': { es: 'Backend para plataformas CRM.', en: 'Backend for CRM platforms.' },
  'Desarrollo backend de aplicaciones CRM.': { es: 'Desarrollo backend de aplicaciones CRM.', en: 'Backend development of CRM applications.' },
  'Aplicaciones Angular.': { es: 'Aplicaciones Angular.', en: 'Angular applications.' },
};

@Injectable({ providedIn: 'root' })
export class Localizacion {
  readonly language = signal<Idioma>(this.readLanguage());

  private readonly activity = inject(ActividadSistema);

  constructor() {
    this.applyDocumentLanguage(this.language());
  }

  setLanguage(idioma: Idioma): void {
    if (this.language() !== idioma) this.activity.pulse('session', 'language');
    this.language.set(idioma);
    this.applyDocumentLanguage(idioma);
    try {
      globalThis.localStorage?.setItem(CLAVE_ALMACENAMIENTO, JSON.stringify({ version: 1, language: idioma }));
    } catch {
      // El idioma puede cambiar durante la sesión aunque no se guarde la preferencia.
    }
  }

  t(clave: ClaveTraduccion, parametros: Record<string, string | number> = {}): string {
    return Object.entries(parametros).reduce(
      (texto, [name, value]) => texto.replaceAll(`{{${name}}}`, String(value)),
      TRADUCCIONES[this.language()][clave],
    );
  }

  applicationLabel(idAplicacion: string): string {
    const clave = CLAVES_ETIQUETAS_APLICACIONES[idAplicacion];
    return clave ? this.t(clave) : idAplicacion;
  }

  windowTitle(estado: { applicationId: string; title: string }): string {
    if (estado.applicationId === 'experience-notepad' || estado.applicationId === 'text-notepad') {
      const nombreArchivo = estado.title.replace(/\s+-\s+(Notepad|Bloc de notas)$/u, '');
      return `${nombreArchivo} - ${this.t('window.notepad')}`;
    }
    if (estado.applicationId === 'image-viewer') {
      const nombreArchivo = estado.title.replace(
        /\s+-\s+(Image Viewer|Visor de imágenes|Viewer|Visor)$/u,
        '',
      );
      return `${nombreArchivo} - ${this.t('window.imageViewer')}`;
    }
    if (estado.applicationId === 'paint') {
      const nombreArchivo = estado.title.replace(/\s+-\s+Paint 98$/u, '');
      return /^(untitled|sin título)$/iu.test(nombreArchivo)
        ? this.t('application.paint.title')
        : `${nombreArchivo} - Paint 98`;
    }

    const clave = CLAVES_TITULOS_APLICACIONES[estado.applicationId];
    return clave ? this.t(clave) : estado.title;
  }

  cvUrl(): string {
    return this.language() === 'en' ? 'CV.en.pdf' : 'CV.pdf';
  }

  cvDownloadName(): string {
    return this.language() === 'en'
      ? 'Daniel_Ramon_Perez_CV_EN.pdf'
      : 'Daniel_Ramon_Perez_CV_ES.pdf';
  }

  localizePortfolio(portfolio: DatosPortfolio): DatosPortfolio {
    return {
      profile: {
        ...portfolio.profile,
        headline: this.content(portfolio.profile.headline),
        location: this.content(portfolio.profile.location),
        summary: this.content(portfolio.profile.summary),
      },
      technologies: portfolio.technologies,
      competencies: portfolio.competencies.map((competencia) => ({
        ...competencia,
        name: this.content(competencia.name),
        evidence: this.content(competencia.evidence),
      })),
      experiences: portfolio.experiences.map((experiencia) => ({
        ...experiencia,
        role: this.content(experiencia.role),
        context: this.content(experiencia.context),
        responsibilities: experiencia.responsibilities.map((elemento) => this.content(elemento)),
        competencies: experiencia.competencies.map((competencia) => ({
          ...competencia,
          name: this.content(competencia.name),
          evidence: this.content(competencia.evidence),
        })),
      })),
      education: portfolio.education.map((formacion) => ({
        ...formacion,
        qualification: this.content(formacion.qualification),
      })),
      languages: portfolio.languages.map((idioma) => ({
        ...idioma,
        language: this.content(idioma.language),
      })),
    };
  }

  private content(valor: string): string {
    return TRADUCCIONES_CONTENIDO[valor]?.[this.language()] ?? valor;
  }

  private readLanguage(): Idioma {
    try {
      const valorGuardado = leerAlmacenamiento(CLAVE_ALMACENAMIENTO);
      if (!valorGuardado) {
        return 'es';
      }
      const guardado = JSON.parse(valorGuardado) as { version?: number; language?: string };
      return guardado.version === 1 && (guardado.language === 'es' || guardado.language === 'en')
        ? guardado.language
        : 'es';
    } catch {
      return 'es';
    }
  }

  private applyDocumentLanguage(idioma: Idioma): void {
    globalThis.document?.documentElement.setAttribute('lang', idioma);
  }
}
