import { AplicacionEscritorio } from '../models/desktop.models';

export const APLICACIONES_ESCRITORIO: readonly AplicacionEscritorio[] = [
  {
    id: 'about',
    label: 'Sobre mí',
    title: 'Sobre mí',
    type: 'about',
    icon: 'computer',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 20 },
    windowConfig: { width: 780, height: 610 },
  },
  {
    id: 'work-experience',
    label: 'Work Experience',
    title: 'Work Experience',
    type: 'explorer',
    icon: 'folder',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 122 },
    windowConfig: { width: 720, height: 480 },
  },
  {
    id: 'linkedin',
    label: 'LinkedIn',
    title: 'LinkedIn',
    type: 'external',
    icon: 'linkedin',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 224 },
  },
  {
    id: 'education',
    label: 'Education.txt',
    title: 'Education.txt - Notepad',
    type: 'notepad',
    icon: 'text-file',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 326 },
    windowConfig: { width: 680, height: 520 },
  },
  {
    id: 'source-code',
    label: 'Source Code',
    title: 'Source Code',
    type: 'external',
    icon: 'source-code',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 428 },
  },
  {
    id: 'pdf-viewer',
    label: 'Daniel_Ramon_Perez_CV.pdf',
    title: 'Daniel_Ramon_Perez_CV.pdf - Viewer',
    type: 'pdf-viewer',
    icon: 'pdf-file',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 530 },
    windowConfig: { width: 920, height: 720 },
  },
  {
    id: 'terminal',
    label: 'Terminal.exe',
    title: 'Terminal.exe',
    type: 'terminal',
    icon: 'terminal',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 632 },
    windowConfig: { width: 700, height: 390 },
  },
  {
    id: 'job-offer',
    label: 'Contratar',
    title: 'Enviar una oferta',
    type: 'job-offer',
    icon: 'mail',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 734 },
    windowConfig: { width: 700, height: 580 },
  },
  {
    id: 'paint',
    label: 'Paint 98',
    title: 'untitled - Paint 98',
    type: 'paint',
    icon: 'paint',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 20 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 940, height: 720 },
  },
  {
    id: 'solitaire',
    label: 'Solitario',
    title: 'Solitario',
    type: 'solitaire',
    icon: 'playing-cards',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 122 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 860, height: 680 },
  },
  {
    id: 'minesweeper',
    label: 'Buscaminas',
    title: 'Buscaminas',
    type: 'minesweeper',
    icon: 'mine',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 224 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 640, height: 610 },
  },
  {
    id: 'message-board',
    label: 'Message Board',
    title: 'Message Board',
    type: 'message-board',
    icon: 'message-board',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 326 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 900, height: 650 },
  },
  {
    id: 'task-manager',
    label: 'Administrador de tareas',
    title: 'Administrador de tareas',
    type: 'task-manager',
    icon: 'task-manager',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 428 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 1020, height: 780 },
  },
  {
    id: 'drp-explorer',
    label: 'DRP Explorer',
    title: 'DRP Explorer',
    type: 'browser',
    icon: 'browser',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 530 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 1040, height: 720 },
  },
  {
    id: 'audio-player',
    label: 'Reproductor',
    title: 'Reproductor',
    type: 'audio-player',
    icon: 'audio-player',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 632 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 900, height: 680 },
  },
  {
    id: 'music-folder',
    label: 'Música',
    title: 'Música',
    type: 'explorer',
    icon: 'folder',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 836 },
    windowConfig: { width: 720, height: 480 },
  },
  {
    id: 'photo-album',
    label: 'Álbum de fotos',
    title: 'Álbum de fotos',
    type: 'explorer',
    icon: 'folder',
    showOnDesktop: true,
    defaultPosition: { x: 1770, y: 734 },
    defaultHorizontalAnchor: 'right',
    windowConfig: { width: 720, height: 480 },
  },
  {
    id: 'recycle-bin',
    label: 'Recycle Bin',
    title: 'Recycle Bin',
    type: 'explorer',
    icon: 'recycle-bin',
    showOnDesktop: true,
    defaultPosition: { x: 34, y: 938 },
    windowConfig: { width: 560, height: 360 },
  },
  {
    id: 'welcome',
    label: 'Welcome',
    title: 'Bienvenido',
    type: 'welcome',
    icon: 'computer',
    showOnDesktop: false,
    windowConfig: { width: 640, height: 500 },
  },
  {
    id: 'experience-notepad',
    label: 'Experience',
    title: 'Experience - Notepad',
    type: 'notepad',
    icon: 'text-file',
    showOnDesktop: false,
    windowConfig: { width: 790, height: 640 },
  },
  {
    id: 'virtual-folder',
    label: 'Folder',
    title: 'Folder',
    type: 'explorer',
    icon: 'folder',
    showOnDesktop: false,
    windowConfig: { width: 720, height: 480 },
  },
  {
    id: 'text-notepad',
    label: 'Text document',
    title: 'Text document - Notepad',
    type: 'notepad',
    icon: 'text-file',
    showOnDesktop: false,
    windowConfig: { width: 700, height: 540 },
  },
  {
    id: 'image-viewer',
    label: 'Image',
    title: 'Image - Viewer',
    type: 'image-viewer',
    icon: 'image-file',
    showOnDesktop: false,
    windowConfig: { width: 760, height: 580 },
  },
  {
    id: 'source-code-message',
    label: 'Source Code',
    title: 'Información',
    type: 'message-box',
    icon: 'source-code',
    showOnDesktop: false,
    windowConfig: { width: 500, height: 240 },
  },
];

export const MAPA_APLICACIONES = new Map(
  APLICACIONES_ESCRITORIO.map((aplicacion) => [aplicacion.id, aplicacion]),
);

export const APLICACIONES_CON_ICONO = APLICACIONES_ESCRITORIO.filter(
  (aplicacion) => aplicacion.showOnDesktop,
);
